-- START NEPAL
use k_strataa;
				-- INSERTING HOUSEHOLD DATA FROM ODK-BASED DATABASE/TABLES INTO STRATAA-DEFINED DATABASE/TABLES  
INSERT IGNORE INTO 
st1_hhlevel(h00_start, h00_end, h00_metaid, h01_mtotal, h02_hhidb, h03_hhidm, h04_site, h05_ta, h06_comm, h07_gpslon, h07_gpslat,
h07_gpsalt, h07_gpsacc, h07_gpsid, h08_phyadr, h08_phyadrid, h09_vdate, h10_iid, h11_tid, h12_hho, h13_infosheet, h14_consent,
h15_respfname, h15_resplname, h15_resphone, h15_resposition, h15_respositionoth, h16_hhhfname, h16_hhhlname, h17_fcontact) 
SELECT 
-- household level
START, END, META_INSTANCE_ID, SECTION_C_TOTAL_MEMBERS, SECTION_B_CONSENT_GROUP_HOUSEHOLD_ID_BARCODE, SECTON_B_CONSENT_GROUP_BARCODE_MANUAL_GRUP_HOUSEHOLD_ID_MANUAL,
SECTION_A_STUDY_SITE, SECTION_A_OTHER_SITE_TRADITIONAL_AUTHORITY, SECTION_A_OTHER_SITE_COMMUNITY, SECTION_A_GEO_LOCATION_GROUP_GEO_LOCATION_LNG, 
SECTION_A_GEO_LOCATION_GROUP_GEO_LOCATION_LAT, SECTION_A_GEO_LOCATION_GROUP_GEO_LOCATION_ALT, SECTION_A_GEO_LOCATION_GROUP_GEO_LOCATION_ACC, 
SECTION_A_GEO_LOCATION_GROUP_GEO_LOCATION_OTHER, SECTION_A_ADDRESS, SECTION_A_ADDRESS_ID, SECTION_A_VISIT_DATE, SECTION_A_INTERVIEWER_GROUP_INTERVIEWER_ID, 
SECTION_A_INTERVIEWER_GROUP_TEAM_ID, SECTION_B_HOUSEHOLD_OCCUPIED, SECTION_B_STUDY_INFO_GIVEN, SECTION_B_CONSENT_GIVEN, 
SECTN_B_CNSNT_GROUP_ANON_RSPNDNT_GRUP_ANON_RESPONDENT_FIRST_NAME, SECTN_B_CNSNT_GROUP_ANON_RSPNDNT_GRUP_ANON_RESPONDENT_SURNAME, 
SECTION_B_CONSENT_GROUP_ANON_PHONE_GROUP_ANON_RESPONDENT_PHONE, SECTION_B_CONSENT_GROUP_RESPONDENT_POSITION, 
SECTION_B_CONSENT_GROUP_RESPONDENT_POSITION_OTHER, SECTNBCNSNTGRPANONHOSHLDNMGRUP_ANON_HEAD_OF_HOUSEHOLD_FIRST_NAME, 
SECTNBCNSNTGRPANONHOSHLDNMGRUP_ANON_HEAD_OF_HOUSEHOLD_SURNAME, SECTION_C_FIRST_CONTACT
-- all ODK tables merged on _TOP LEVEL AURI
FROM odk_prod.CENSUS_V1_2_CORE, odk_prod.CENSUS_V1_2_CORE2, odk_prod.CENSUS_V1_2_CORE3, odk_prod.CENSUS_V1_2_CORE4, 
odk_prod.CENSUS_V1_2_CORE5, odk_prod.CENSUS_V1_2_CORE6, odk_prod.CENSUS_V1_2_CORE7, odk_prod.CENSUS_V1_2_CORE8, 
odk_prod.CENSUS_V1_2_CORE9, odk_prod.CENSUS_V1_2_CORE10
WHERE NOT EXISTS (SELECT 1 FROM st9_auditlog c WHERE c.metaid = CENSUS_V1_2_CORE._URI) AND
CENSUS_V1_2_CORE._URI = CENSUS_V1_2_CORE2._TOP_LEVEL_AURI AND CENSUS_V1_2_CORE2._TOP_LEVEL_AURI = CENSUS_V1_2_CORE3._TOP_LEVEL_AURI
AND CENSUS_V1_2_CORE3._TOP_LEVEL_AURI = CENSUS_V1_2_CORE4._TOP_LEVEL_AURI AND CENSUS_V1_2_CORE4._TOP_LEVEL_AURI = CENSUS_V1_2_CORE5._TOP_LEVEL_AURI 
AND CENSUS_V1_2_CORE5._TOP_LEVEL_AURI = CENSUS_V1_2_CORE6._TOP_LEVEL_AURI AND CENSUS_V1_2_CORE6._TOP_LEVEL_AURI = CENSUS_V1_2_CORE7._TOP_LEVEL_AURI
AND CENSUS_V1_2_CORE7._TOP_LEVEL_AURI = CENSUS_V1_2_CORE8._TOP_LEVEL_AURI AND CENSUS_V1_2_CORE8._TOP_LEVEL_AURI = CENSUS_V1_2_CORE9._TOP_LEVEL_AURI
AND CENSUS_V1_2_CORE9._TOP_LEVEL_AURI = CENSUS_V1_2_CORE10._TOP_LEVEL_AURI;
-- END NEPAL
