/* Creates the Audit Log Table in your database */
USE k_strataa;
DROP TABLE IF EXISTS `st9_auditlog`;
CREATE TABLE `st9_auditlog` ( 
  `id` INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (id),
  `metaid` Varchar(255) NOT NULL,
  `table_name` varchar(20) NOT NULL,
  `action` varchar(20) default NULL,
  `row_pk1` varchar(20) default NULL, 
  `row_pk2` varchar(20) default NULL, 
  `field_name` varchar(50) default NULL,
  `old_value` varchar(250) default NULL,
  `new_value` varchar(250) default NULL,
  `timestamp` varchar(100) default NULL,
  `user` varchar(100) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='General logging table.';

/* Triggers Census household level */
DROP TRIGGER IF EXISTS `update_st1_hhlevel`;
DELIMITER $$
CREATE TRIGGER `update_st1_hhlevel` AFTER UPDATE ON `st1_hhlevel` FOR EACH ROW
BEGIN
IF (NEW.h00_start != OLD.h00_start) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h00_start", OLD.h00_start, NEW.h00_start, NOW(), CURRENT_USER); END IF;
IF (NEW.h00_end != OLD.h00_end) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h00_end", OLD.h00_end, NEW.h00_end, NOW(), CURRENT_USER); END IF;
IF (NEW.h00_metaid != OLD.h00_metaid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h00_metaid", OLD.h00_metaid, NEW.h00_metaid, NOW(), CURRENT_USER); END IF;
IF (NEW.h01_mtotal != OLD.h01_mtotal) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h01_mtotal", OLD.h01_mtotal, NEW.h01_mtotal, NOW(), CURRENT_USER); END IF;
IF (NEW.h02_hhidb != OLD.h02_hhidb) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h02_hhidb", OLD.h02_hhidb, NEW.h02_hhidb, NOW(), CURRENT_USER); END IF;
IF (NEW.h03_hhidm != OLD.h03_hhidm) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h03_hhidm", OLD.h03_hhidm, NEW.h03_hhidm, NOW(), CURRENT_USER); END IF;
IF (NEW.h04_site != OLD.h04_site) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h04_site", OLD.h04_site, NEW.h04_site, NOW(), CURRENT_USER); END IF;
IF (NEW.h05_ta != OLD.h05_ta) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h05_ta", OLD.h05_ta, NEW.h05_ta, NOW(), CURRENT_USER); END IF;
IF (NEW.h06_comm != OLD.h06_comm) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h06_comm", OLD.h06_comm, NEW.h06_comm, NOW(), CURRENT_USER); END IF;
IF (NEW.h07_gpslon != OLD.h07_gpslon) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h07_gpslon", OLD.h07_gpslon, NEW.h07_gpslon, NOW(), CURRENT_USER); END IF;
IF (NEW.h07_gpslat != OLD.h07_gpslat) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h07_gpslat", OLD.h07_gpslat, NEW.h07_gpslat, NOW(), CURRENT_USER); END IF;
IF (NEW.h07_gpsalt != OLD.h07_gpsalt) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h07_gpsalt", OLD.h07_gpsalt, NEW.h07_gpsalt, NOW(), CURRENT_USER); END IF;
IF (NEW.h07_gpsacc != OLD.h07_gpsacc) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h07_gpsacc", OLD.h07_gpsacc, NEW.h07_gpsacc, NOW(), CURRENT_USER); END IF;
IF (NEW.h07_gpsid != OLD.h07_gpsid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h07_gpsid", OLD.h07_gpsid, NEW.h07_gpsid, NOW(), CURRENT_USER); END IF;
IF (NEW.h08_phyadr != OLD.h08_phyadr) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h08_phyadr", OLD.h08_phyadr, NEW.h08_phyadr, NOW(), CURRENT_USER); END IF;
IF (NEW.h08_phyadrid != OLD.h08_phyadrid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h08_phyadrid", OLD.h08_phyadrid, NEW.h08_phyadrid, NOW(), CURRENT_USER); END IF;
IF (NEW.h09_vdate != OLD.h09_vdate) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h09_vdate", OLD.h09_vdate, NEW.h09_vdate, NOW(), CURRENT_USER); END IF;
IF (NEW.h10_iid != OLD.h10_iid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h10_iid", OLD.h10_iid, NEW.h10_iid, NOW(), CURRENT_USER); END IF;
IF (NEW.h11_tid != OLD.h11_tid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h11_tid", OLD.h11_tid, NEW.h11_tid, NOW(), CURRENT_USER); END IF;
IF (NEW.h12_hho != OLD.h12_hho) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h12_hho", OLD.h12_hho, NEW.h12_hho, NOW(), CURRENT_USER); END IF;
IF (NEW.h13_infosheet != OLD.h13_infosheet) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h00_start, "h13_infosheet", OLD.h13_infosheet, NEW.h13_infosheet, NOW(), CURRENT_USER); END IF;
IF (NEW.h14_consent != OLD.h14_consent) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h14_consent", OLD.h14_consent, NEW.h14_consent, NOW(), CURRENT_USER); END IF;
IF (NEW.h15_respfname != OLD.h15_respfname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h15_respfname", OLD.h15_respfname, NEW.h15_respfname, NOW(), CURRENT_USER); END IF;
IF (NEW.h15_resplname != OLD.h15_resplname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h15_resplname", OLD.h15_resplname, NEW.h15_resplname, NOW(), CURRENT_USER); END IF;
IF (NEW.h15_resphone != OLD.h15_resphone) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h15_resphone", OLD.h15_resphone, NEW.h15_resphone, NOW(), CURRENT_USER); END IF;
IF (NEW.h15_resposition != OLD.h15_resposition) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h15_resposition", OLD.h15_resposition, NEW.h15_resposition, NOW(), CURRENT_USER); END IF;
IF (NEW.h15_respositionoth != OLD.h15_respositionoth) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h15_respositionoth", OLD.h15_respositionoth, NEW.h15_respositionoth, NOW(), CURRENT_USER); END IF;
IF (NEW.h16_hhhfname != OLD.h16_hhhfname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h16_hhhfname", OLD.h16_hhhfname, NEW.h16_hhhfname, NOW(), CURRENT_USER); END IF;
IF (NEW.h16_hhhlname != OLD.h16_hhhlname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h16_hhhlname", OLD.h16_hhhlname, NEW.h16_hhhlname, NOW(), CURRENT_USER); END IF;
IF (NEW.h17_fcontact != OLD.h17_fcontact) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "updated", OLD.h02_hhidb, OLD.h03_hhidm, "h17_fcontact", OLD.h17_fcontact, NEW.h17_fcontact, NOW(), CURRENT_USER); END IF;
END;$$
DELIMITER ;
DELIMITER $$
DROP TRIGGER IF EXISTS `delete_st1_hhlevel` $$
CREATE TRIGGER `delete_st1_hhlevel` BEFORE DELETE on `st1_hhlevel` FOR EACH ROW
BEGIN
INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.h00_metaid, "st1_hhlevel", "deleted", OLD.h02_hhidb, OLD.h03_hhidm, "all_fields", "n/a", "n/a", NOW(), CURRENT_USER);END$$
DELIMITER ;

/* Triggers Census member level */
DROP TRIGGER IF EXISTS `update_st2_mmlevel`;
DELIMITER $$
CREATE TRIGGER `update_st2_mmlevel` AFTER UPDATE ON `st2_mmlevel` FOR EACH ROW
BEGIN
IF (NEW.m00_metaid != OLD.m00_metaid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m00_metaid", OLD.m00_metaid, NEW.m00_metaid, NOW(), CURRENT_USER); END IF;
IF (NEW.m01_hhidb != OLD.m01_hhidb) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m01_hhidb", OLD.m01_hhidb, NEW.m01_hhidb, NOW(), CURRENT_USER); END IF;
IF (NEW.m02_hhidm != OLD.m02_hhidm) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m02_hhidm", OLD.m02_hhidm, NEW.m02_hhidm, NOW(), CURRENT_USER); END IF;
IF (NEW.m03_hhmno != OLD.m03_hhmno) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m03_hhmno", OLD.m03_hhmno, NEW.m03_hhmno, NOW(), CURRENT_USER); END IF;
IF (NEW.m03_hhmid != OLD.m03_hhmid) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m03_hhmid", OLD.m03_hhmid, NEW.m03_hhmid, NOW(), CURRENT_USER); END IF;
IF (NEW.m04_mfname != OLD.m04_mfname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m04_mfname", OLD.m04_mfname, NEW.m04_mfname, NOW(), CURRENT_USER); END IF;
IF (NEW.m05_mlname != OLD.m05_mlname) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m05_mlname", OLD.m05_mlname, NEW.m05_mlname, NOW(), CURRENT_USER); END IF;
IF (NEW.m06_mphone != OLD.m06_mphone) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m06_mphone", OLD.m06_mphone, NEW.m06_mphone, NOW(), CURRENT_USER); END IF;
IF (NEW.m07_ethnic != OLD.m07_ethnic) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m07_ethnic", OLD.m07_ethnic, NEW.m07_ethnic, NOW(), CURRENT_USER); END IF;
IF (NEW.m08_othethnic != OLD.m08_othethnic) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m08_othethnic", OLD.m08_othethnic, NEW.m08_othethnic, NOW(), CURRENT_USER); END IF;
IF (NEW.m09_sex != OLD.m09_sex) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m09_sex", OLD.m09_sex, NEW.m09_sex, NOW(), CURRENT_USER); END IF;
IF (NEW.m10_kdob != OLD.m10_kdob) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m10_kdob", OLD.m10_kdob, NEW.m10_kdob, NOW(), CURRENT_USER); END IF;
IF (NEW.m11_ageyrs != OLD.m11_ageyrs) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m11_ageyrs", OLD.m11_ageyrs, NEW.m11_ageyrs, NOW(), CURRENT_USER); END IF;
IF (NEW.m12_agemos != OLD.m12_agemos) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m12_agemos", OLD.m12_agemos, NEW.m12_agemos, NOW(), CURRENT_USER); END IF;
IF (NEW.m13_dob != OLD.m13_dob) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m13_dob", OLD.m13_dob, NEW.m13_dob, NOW(), CURRENT_USER); END IF;
IF (NEW.m14_hhhrel != OLD.m14_hhhrel) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m14_hhhrel", OLD.m14_hhhrel, NEW.m14_hhhrel, NOW(), CURRENT_USER); END IF;
IF (NEW.m15_hhhreloth != OLD.m15_hhhreloth) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m15_hhhreloth", OLD.m15_hhhreloth, NEW.m15_hhhreloth, NOW(), CURRENT_USER); END IF;
IF (NEW.m16_xool != OLD.m16_xool) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m16_xool", OLD.m16_xool, NEW.m16_xool, NOW(), CURRENT_USER); END IF;
IF (NEW.m17_edu != OLD.m17_edu) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m17_edu", OLD.m17_edu, NEW.m17_edu, NOW(), CURRENT_USER); END IF;
IF (NEW.m18_empl != OLD.m18_empl) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m18_empl", OLD.m18_empl, NEW.m18_empl, NOW(), CURRENT_USER); END IF;
IF (NEW.m19_othempl != OLD.m19_othempl) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m19_othempl", OLD.m19_othempl, NEW.m19_othempl, NOW(), CURRENT_USER); END IF;
IF (NEW.m20_add != OLD.m20_add) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m20_add", OLD.m20_add, NEW.m20_add, NOW(), CURRENT_USER); END IF;
IF (NEW.m21_mmno != OLD.m21_mmno) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m21_mmno", OLD.m21_mmno, NEW.m21_mmno, NOW(), CURRENT_USER); END IF;
IF (NEW.m22_fmno != OLD.m22_fmno) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m22_fmno", OLD.m22_fmno, NEW.m22_fmno, NOW(), CURRENT_USER); END IF;
IF (NEW.m23_ms != OLD.m23_ms) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m23_ms", OLD.m23_ms, NEW.m23_ms, NOW(), CURRENT_USER); END IF;
IF (NEW.m24_smno != OLD.m24_smno) THEN INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "updated", OLD.m01_hhidb, OLD.m02_hhidm, "m24_smno", OLD.m24_smno, NEW.m24_smno, NOW(), CURRENT_USER); END IF;
END;$$
DELIMITER ;
DELIMITER $$
DROP TRIGGER IF EXISTS `delete_st2_mmlevel` $$
CREATE TRIGGER `delete_st2_mmlevel` BEFORE DELETE on `st2_mmlevel` FOR EACH ROW
BEGIN
INSERT INTO st9_auditlog (`metaid`, `table_name`, `action`, `row_pk1`, `row_pk2`, `field_name`, `old_value`, `new_value`, `timestamp`,`user`) VALUES (OLD.m00_metaid, "st2_mmlevel", "deleted", OLD.m01_hhidb, OLD.m02_hhidm, "all_fields", "n/a", "n/a", NOW(), CURRENT_USER);END$$
DELIMITER ;